language: python
sudo: false
env:
  - TOXENV=pep8
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=doc
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
notifications:
    email:
        on_success: change
        on_failure: always
