language: python
sudo: false
env:
  global:
    - REDIS_HOST=localhost
  matrix:
    - TOXENV=pep8
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=doc
services:
  - redis-server
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
notifications:
    email:
        on_success: change
        on_failure: always
